// export interface Lesson {
//   id: string;
//   title: string;
//   duration: string;
//   completed: boolean;
//   videoUrl: string;
//   isPreview?: boolean;
// }

// export interface Course {
//   id: string;
//   title: string;
//   instructor: string;
//   description: string;
//   duration: string;
//   lessons: number;
//   rating: number;
//   students: string | number;
//   lastUpdated: string;
//   image: string;
//   price: string;
//   originalPrice: string;
//   category: string;
//   isTopAuthor?: boolean;
//   lessons_list: Lesson[];
// }

// export const COURSES: Course[] = [
//   {
//     id: "1",
//     title: "Mastering React Native Animation",
//     instructor: "Sarah Johnson",
//     description: "Learn advanced animation techniques in React Native to create stunning user experiences. This course covers everything from simple transitions to complex gesture-based interactions.",
//     duration: "8h 15m",
//     lessons: 5,
//     rating: 4.8,
//     students: "1,234",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2670&auto=format&fit=crop",
//     price: "$10.99",
//     originalPrice: "$32",
//     category: "Development",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Introduction to Animations",
//         duration: "12:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Understanding Animated API",
//         duration: "18:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Spring Animations",
//         duration: "15:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Timing Animations",
//         duration: "20:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Gesture-Based Animations",
//         duration: "25:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//     ],
//   },
//   {
//     id: "2",
//     title: "Fullstack Development with Expo",
//     instructor: "Michael Chen",
//     description: "Build complete mobile applications with Expo and modern backend technologies. A comprehensive guide to building scalable apps.",
//     duration: "12h 45m",
//     lessons: 36,
//     rating: 4.9,
//     students: "2,156",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=2672&auto=format&fit=crop",
//     price: "$10.99",
//     originalPrice: "$32",
//     category: "Development",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Getting Started with Expo",
//         duration: "10:00",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Setting Up Backend",
//         duration: "22:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "API Integration",
//         duration: "18:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//     ],
//   },
//   {
//     id: "3",
//     title: "TypeScript for Beginners",
//     instructor: "Elena Rodriguez",
//     description: "Master TypeScript fundamentals and advanced concepts for modern development. Essential for any React Native developer.",
//     duration: "6h",
//     lessons: 18,
//     rating: 4.7,
//     students: "3,421",
//     lastUpdated: "Mar 2024",
//     image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2728&auto=format&fit=crop",
//     price: "$59.99",
//     originalPrice: "$89",
//     category: "Development",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "TypeScript Basics",
//         duration: "14:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Types and Interfaces",
//         duration: "16:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Generics",
//         duration: "19:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//     ],
//   },
//   {
//     id: "4",
//     title: "JavaScript for Modern Web",
//     instructor: "Robert Fox",
//     description: "Master JavaScript ES6+ and build interactive web applications with ease.",
//     duration: "10h",
//     lessons: 25,
//     rating: 4.5,
//     students: "2,980",
//     lastUpdated: "Dec 2023",
//     image: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=2670&auto=format&fit=crop",
//     price: "$10.99",
//     originalPrice: "$32",
//     category: "Development",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Closures and Scope",
//         duration: "20:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Prototypal Inheritance",
//         duration: "18:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "5",
//     title: "UI/UX Design Fundamentals",
//     instructor: "Amanda Foster",
//     description: "Learn the principles of great UI/UX design. Create beautiful, user-friendly interfaces that users love.",
//     duration: "7h 45m",
//     lessons: 15,
//     rating: 4.8,
//     students: "2,890",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2664&auto=format&fit=crop",
//     price: "$44.99",
//     originalPrice: "$79",
//     category: "Design",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Design Principles",
//         duration: "15:00",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Color Theory",
//         duration: "12:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "6",
//     title: "Node.js Backend Development",
//     instructor: "James Wilson",
//     description: "Build robust backend APIs with Node.js and Express. Learn authentication, database integration, and deployment.",
//     duration: "14h 20m",
//     lessons: 32,
//     rating: 4.9,
//     students: "5,234",
//     lastUpdated: "Mar 2024",
//     image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2734&auto=format&fit=crop",
//     price: "$69.99",
//     originalPrice: "$99",
//     category: "Development",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Setting Up Node.js",
//         duration: "10:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Express Fundamentals",
//         duration: "22:00",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "7",
//     title: "React Hooks Mastery",
//     instructor: "Lisa Anderson",
//     description: "Master React Hooks from basics to advanced patterns. Build modern React applications with confidence.",
//     duration: "9h 15m",
//     lessons: 20,
//     rating: 4.8,
//     students: "3,876",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2670&auto=format&fit=crop",
//     price: "$54.99",
//     originalPrice: "$84",
//     category: "Development",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "useState and useEffect",
//         duration: "16:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Custom Hooks",
//         duration: "19:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "8",
//     title: "Mobile App Performance Optimization",
//     instructor: "Robert Martinez",
//     description: "Learn techniques to optimize React Native apps for maximum performance. Reduce load times and improve user experience.",
//     duration: "5h 30m",
//     lessons: 12,
//     rating: 4.7,
//     students: "1,987",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
//     price: "$34.99",
//     originalPrice: "$59",
//     category: "Development",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Performance Profiling",
//         duration: "14:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Memory Management",
//         duration: "18:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "9",
//     title: "GraphQL API Development",
//     instructor: "Sophie Turner",
//     description: "Build modern APIs with GraphQL. Learn queries, mutations, subscriptions, and best practices for scalable applications.",
//     duration: "11h 00m",
//     lessons: 28,
//     rating: 4.9,
//     students: "2,654",
//     lastUpdated: "Mar 2024",
//     image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2670&auto=format&fit=crop",
//     price: "$64.99",
//     originalPrice: "$94",
//     category: "Development",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "GraphQL Basics",
//         duration: "12:00",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Schema Design",
//         duration: "20:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   {
//     id: "10",
//     title: "Testing React Native Apps",
//     instructor: "Chris Thompson",
//     description: "Comprehensive guide to testing React Native applications. Learn unit testing, integration testing, and E2E testing.",
//     duration: "8h 45m",
//     lessons: 22,
//     rating: 4.8,
//     students: "3,145",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2670&auto=format&fit=crop",
//     price: "$49.99",
//     originalPrice: "$74",
//     category: "Development",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Jest Fundamentals",
//         duration: "15:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "React Testing Library",
//         duration: "17:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//     ],
//   },
//   // Design Courses
//   {
//     id: "11",
//     title: "Advanced UI/UX Design Principles",
//     instructor: "Sarah Chen",
//     description: "Master advanced UI/UX design principles and create stunning user experiences",
//     duration: "8h 30m",
//     lessons: 6,
//     rating: 4.9,
//     students: "12,456",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2664&auto=format&fit=crop",
//     price: "$59.99",
//     originalPrice: "$89",
//     category: "Design",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Design Thinking Process",
//         duration: "14:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "User Research Methods",
//         duration: "16:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Wireframing & Prototyping",
//         duration: "18:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Visual Design Principles",
//         duration: "20:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Usability Testing",
//         duration: "15:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Design Systems",
//         duration: "22:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//     ],
//   },
//   {
//     id: "12",
//     title: "Graphic Design Masterclass",
//     instructor: "David Martinez",
//     description: "Learn professional graphic design from basics to advanced techniques",
//     duration: "10h 15m",
//     lessons: 7,
//     rating: 4.8,
//     students: "9,234",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?q=80&w=2671&auto=format&fit=crop",
//     price: "$54.99",
//     originalPrice: "$79",
//     category: "Design",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Typography Fundamentals",
//         duration: "16:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Color Theory",
//         duration: "14:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Logo Design",
//         duration: "19:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Brand Identity",
//         duration: "21:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Layout & Composition",
//         duration: "17:35",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Adobe Creative Suite",
//         duration: "23:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "Portfolio Building",
//         duration: "15:25",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//     ],
//   },
//   // Business Courses
//   {
//     id: "13",
//     title: "Entrepreneurship 101",
//     instructor: "Mark Johnson",
//     description: "Start and grow your business with proven strategies and frameworks",
//     duration: "9h 45m",
//     lessons: 6,
//     rating: 4.9,
//     students: "15,678",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2670&auto=format&fit=crop",
//     price: "$64.99",
//     originalPrice: "$99",
//     category: "Business",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Finding Your Business Idea",
//         duration: "18:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Market Research",
//         duration: "20:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Business Planning",
//         duration: "22:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Funding & Finance",
//         duration: "19:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Building Your Team",
//         duration: "17:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Scaling Your Business",
//         duration: "24:50",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//     ],
//   },
//   {
//     id: "14",
//     title: "Project Management Professional",
//     instructor: "Jennifer Lee",
//     description: "Master project management methodologies including Agile, Scrum, and PMP",
//     duration: "11h 20m",
//     lessons: 8,
//     rating: 4.8,
//     students: "11,234",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?q=80&w=2670&auto=format&fit=crop",
//     price: "$69.99",
//     originalPrice: "$109",
//     category: "Business",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "PM Fundamentals",
//         duration: "15:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Agile Methodology",
//         duration: "18:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Scrum Framework",
//         duration: "16:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Risk Management",
//         duration: "17:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Stakeholder Communication",
//         duration: "14:35",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Resource Planning",
//         duration: "19:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "Quality Management",
//         duration: "16:55",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//       {
//         id: "8",
//         title: "PMP Exam Prep",
//         duration: "21:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//       },
//     ],
//   },
//   {
//     id: "15",
//     title: "Financial Analysis & Modeling",
//     instructor: "Robert Chen",
//     description: "Learn financial analysis, modeling, and valuation techniques",
//     duration: "10h 30m",
//     lessons: 7,
//     rating: 4.7,
//     students: "8,567",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
//     price: "$74.99",
//     originalPrice: "$119",
//     category: "Business",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Financial Statements",
//         duration: "17:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Ratio Analysis",
//         duration: "16:25",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "DCF Modeling",
//         duration: "20:50",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Company Valuation",
//         duration: "19:35",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Excel for Finance",
//         duration: "18:15",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Investment Analysis",
//         duration: "21:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "Strategic Finance",
//         duration: "22:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//     ],
//   },
//   // Marketing Courses
//   {
//     id: "16",
//     title: "Digital Marketing Mastery",
//     instructor: "Emma Wilson",
//     description: "Complete digital marketing course covering all channels and strategies",
//     duration: "12h 15m",
//     lessons: 9,
//     rating: 4.9,
//     students: "18,234",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
//     price: "$59.99",
//     originalPrice: "$99",
//     category: "Marketing",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Digital Marketing Overview",
//         duration: "14:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Content Marketing",
//         duration: "16:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Social Media Marketing",
//         duration: "18:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Email Marketing",
//         duration: "15:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "PPC Advertising",
//         duration: "17:55",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Analytics & Tracking",
//         duration: "19:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "Conversion Optimization",
//         duration: "16:25",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//       {
//         id: "8",
//         title: "Marketing Automation",
//         duration: "20:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//       },
//       {
//         id: "9",
//         title: "Marketing Strategy",
//         duration: "21:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//     ],
//   },
//   {
//     id: "17",
//     title: "SEO Complete Guide 2024",
//     instructor: "Alex Turner",
//     description: "Master Search Engine Optimization and rank #1 on Google",
//     duration: "9h 40m",
//     lessons: 7,
//     rating: 4.8,
//     students: "14,567",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?q=80&w=2674&auto=format&fit=crop",
//     price: "$54.99",
//     originalPrice: "$84",
//     category: "Marketing",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "SEO Fundamentals",
//         duration: "15:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Keyword Research",
//         duration: "17:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "On-Page SEO",
//         duration: "19:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Technical SEO",
//         duration: "21:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Link Building",
//         duration: "18:25",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Local SEO",
//         duration: "16:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "SEO Tools & Analytics",
//         duration: "20:55",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//     ],
//   },
//   {
//     id: "18",
//     title: "Social Media Marketing Pro",
//     instructor: "Sophia Rodriguez",
//     description: "Build engaged communities and drive sales through social media",
//     duration: "8h 50m",
//     lessons: 6,
//     rating: 4.7,
//     students: "10,892",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=2574&auto=format&fit=crop",
//     price: "$49.99",
//     originalPrice: "$74",
//     category: "Marketing",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Social Media Strategy",
//         duration: "16:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Instagram Marketing",
//         duration: "18:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Facebook Ads",
//         duration: "20:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "LinkedIn for Business",
//         duration: "17:35",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "TikTok Marketing",
//         duration: "15:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Influencer Marketing",
//         duration: "19:50",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//     ],
//   },
//   // Health Courses
//   {
//     id: "19",
//     title: "Nutrition & Wellness Fundamentals",
//     instructor: "Dr. Lisa Anderson",
//     description: "Science-based nutrition and wellness strategies for optimal health",
//     duration: "7h 30m",
//     lessons: 6,
//     rating: 4.9,
//     students: "13,456",
//     lastUpdated: "Jan 2024",
//     image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=2653&auto=format&fit=crop",
//     price: "$44.99",
//     originalPrice: "$69",
//     category: "Health",
//     isTopAuthor: true,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Nutrition Basics",
//         duration: "14:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Macronutrients",
//         duration: "16:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Micronutrients & Vitamins",
//         duration: "15:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Meal Planning",
//         duration: "17:10",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Healthy Eating Habits",
//         duration: "14:55",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Wellness Lifestyle",
//         duration: "18:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//     ],
//   },
//   {
//     id: "20",
//     title: "Fitness Training Complete Course",
//     instructor: "Mike Thompson",
//     description: "Complete fitness training covering strength, cardio, and flexibility",
//     duration: "9h 15m",
//     lessons: 7,
//     rating: 4.8,
//     students: "11,789",
//     lastUpdated: "Feb 2024",
//     image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=2670&auto=format&fit=crop",
//     price: "$49.99",
//     originalPrice: "$79",
//     category: "Health",
//     isTopAuthor: false,
//     lessons_list: [
//       {
//         id: "1",
//         isPreview: true,
//         title: "Fitness Fundamentals",
//         duration: "15:30",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//       },
//       {
//         id: "2",
//         title: "Strength Training",
//         duration: "18:45",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//       },
//       {
//         id: "3",
//         title: "Cardio Workouts",
//         duration: "16:20",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//       },
//       {
//         id: "4",
//         title: "Flexibility & Mobility",
//         duration: "14:35",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//       },
//       {
//         id: "5",
//         title: "Workout Programming",
//         duration: "19:40",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//       },
//       {
//         id: "6",
//         title: "Recovery & Rest",
//         duration: "13:25",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//       },
//       {
//         id: "7",
//         title: "Nutrition for Athletes",
//         duration: "17:50",
//         completed: false,
//         videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//       },
//     ],
//   },
// ];
